name: Build Laravel with Docker

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build \
            --file dockerfile-php \
            --tag laravel-app:ci \
            .

      - name: Build frontend assets inside Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/var/www/html \
            laravel-app:ci \
            sh -c "npm install && npm run build"
